INSERT INTO projects (title) VALUES ('project 1');
INSERT INTO projects (title) VALUES ('project 2');
INSERT INTO projects (title) VALUES ('project 3');
INSERT INTO projects (title) VALUES ('project 4');
INSERT INTO projects (title) VALUES ('project 5');
INSERT INTO projects (title) VALUES ('project 6');
INSERT INTO projects (title) VALUES ('project 7');
INSERT INTO projects (title) VALUES ('project 8');
INSERT INTO projects (title) VALUES ('project 9');
INSERT INTO projects (title) VALUES ('project 10');

INSERT INTO users (name) VALUES ('name 1');
INSERT INTO users (name) VALUES ('name 2');
INSERT INTO users (name) VALUES ('name 3');
INSERT INTO users (name) VALUES ('name 4');
INSERT INTO users (name) VALUES ('name 5');
INSERT INTO users (name) VALUES ('name 6');
INSERT INTO users (name) VALUES ('name 7');
INSERT INTO users (name) VALUES ('name 8');
INSERT INTO users (name) VALUES ('name 9');
INSERT INTO users (name) VALUES ('name 10');
INSERT INTO users (name) VALUES ('name 11');
INSERT INTO users (name) VALUES ('name 12');
INSERT INTO users (name) VALUES ('name 13');
INSERT INTO users (name) VALUES ('name 14');
INSERT INTO users (name) VALUES ('name 15');
INSERT INTO users (name) VALUES ('name 16');
INSERT INTO users (name) VALUES ('name 17');
INSERT INTO users (name) VALUES ('name 18');
INSERT INTO users (name) VALUES ('name 19');
INSERT INTO users (name) VALUES ('name 20');

INSERT INTO pledges (amount) VALUES (1000);
INSERT INTO pledges (amount) VALUES (1000);
INSERT INTO pledges (amount) VALUES (1000);
INSERT INTO pledges (amount) VALUES (1000);
INSERT INTO pledges (amount) VALUES (1000);
INSERT INTO pledges (amount) VALUES (1000);
INSERT INTO pledges (amount) VALUES (1000);
INSERT INTO pledges (amount) VALUES (1000);
INSERT INTO pledges (amount) VALUES (1000);
INSERT INTO pledges (amount) VALUES (1000);
INSERT INTO pledges (amount) VALUES (1);
INSERT INTO pledges (amount) VALUES (1);
INSERT INTO pledges (amount) VALUES (1);
INSERT INTO pledges (amount) VALUES (1);
INSERT INTO pledges (amount) VALUES (1);
INSERT INTO pledges (amount) VALUES (1);
INSERT INTO pledges (amount) VALUES (1);
INSERT INTO pledges (amount) VALUES (1);
INSERT INTO pledges (amount) VALUES (1);
INSERT INTO pledges (amount) VALUES (1);
INSERT INTO pledges (amount) VALUES (10);
INSERT INTO pledges (amount) VALUES (10);
INSERT INTO pledges (amount) VALUES (10);
INSERT INTO pledges (amount) VALUES (10);
INSERT INTO pledges (amount) VALUES (10);
INSERT INTO pledges (amount) VALUES (10);
INSERT INTO pledges (amount) VALUES (10);
INSERT INTO pledges (amount) VALUES (10);
INSERT INTO pledges (amount) VALUES (10);
INSERT INTO pledges (amount) VALUES (10);
